### ISSUE TITLE
windows7 import modules of installed app from app_packages

### ISSUE THREAD

**Issue by hdm-dt-fb** [pybee/briefcase#102]
First off, thank you for the awesome beeware projects!!

I built a little gui toga helper app for my colleagues, that helps 
them archiving their mails from Outlook in a more efficient way.
(for that I use the non-std packages psutil and pywin32)

The app works well on my dev machine (windows7 python 3.6) 
straight from the IDE(pyCharm), but when I install it, the installed 
app refuses to load.
The temperature converter from the examples does not have that 
issue and also works installed.

So I went ahead and redirected stderr to a text file: 
(maybe this is worth adding into a troubleshooting section in readthedocs(?))
`python/pythonw.exe app/start.py 1>stdout.txt 2>stderr.txt`
according to this SO post:
https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe#30313091
This showed me that the modules could not be found by pythonw 
although they were nicely downloaded packaged up in app_packages.
As a quick&dirty test I threw in:
```python
import sys
print("pre_imports")

for p in sys.path:
    print(p)

app_pkg = "D:/outlook_mail_exporter/windows/content/app_packages"
w32_dir = os.path.join(app_pkg, "win32")
w32_lib_dir = os.path.join(w32_dir, "lib")
sys.path.extend([app_pkg, w32_dir, w32_lib_dir])

for p in sys.path:
    print(p)

import pywintypes
print("pywintypes imported!")
import win32api
print("winapi32 imported!")
```
to find that the app actually works, if append the path to sys as shown above. 
I am a bit puzzled by this behavior, as this seems to be what start.py is doing already?
Do you have an idea/hint why I needed the extra sys-path appends?
Thank you!

**Comment by hdm-dt-fb** [comment]
..maybe related to #46 ?

**Comment by andrewleech** [comment]
Over the years pywin32 module has often had issues with the path and imports due to the different ways it's tried to install and then find it's bundled DLL libraries. 
Your issue is probably related to this.

The actual error message when it fails, doors it refer to not being able to lead a DLL? 

Either way, of your path changes above work I wouldn't worry about it too much. 

I can check on Monday what we do for pywin32 if it helps. I know I've got some manual path fixups to work when running from source, can't remember if I had to fix it for running from briefcase... although I've rewritten start.py to work with our application compiled through nuitka rather than from source.

**Comment by hdm-dt-fb** [comment]
Ah I see. 
Well then I guess it is a pywin32 thing - so I just leave a nicer version of my sys path fix in.. (-:
Thanks a lot!

btw:
It seems (without my fix) that it gets until the `__init__.py` of win32com and gets stuck there (so no dlls involved):
```python
Traceback (most recent call last):
  File "app\start.py", line 9, in <module>
    from outlook_mail_exporter.app import main
  File "app\outlook_mail_exporter\app.py", line 24, in <module>
    import win32com.client
  File "app_packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ModuleNotFoundError: No module named 'win32api'

```
