### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by Jvalal** [pybee/briefcase#158]
Getting an error trying to follow the tutorial.

<img width="920" alt="screen shot 2018-08-13 at 8 23 22 pm" src="https://user-images.githubusercontent.com/3803053/44070118-e9131254-9f36-11e8-9b47-85cd7d731996.png">

**Comment by freakboy3742** [comment]
The error would seem to be fairly clear from the error message - "Briefcase requires Python 3.4+". I'm guessing you're running the tutorial on Python 2.

Both the getting started guide and the tutorial mention that Python 3 is a prerequisite. 

If there's something we can do to make this requirement (or the error message) more obvious, we're open to suggestions; but there is a practical limit to how much we can do.

**Comment by Jvalal** [comment]
No. I'm running 3.7.  So it's not "fairly clear". 

<img width="758" alt="screen shot 2018-08-13 at 9 17 09 pm" src="https://user-images.githubusercontent.com/3803053/44071510-4b9af12e-9f3e-11e8-854b-3d79215ca5cf.png">

**Comment by freakboy3742** [comment]
Ah - so now you've provided some helpful context that wasn't in your original report. That gives us something to work with.

However, I'm still inclined to suggest the issue is that you're running on Python 2. I don't recognise the IDE you're using by sight, but just because there's a Python version in your project doesn't mean that's the version being executed. The Python version is being enforced by setup tools itself, not Briefcase, so either the Python version active in your shell is Python 2, or the version of pip that is being executed is tied to a python2 installation.

I don't know how your IDE operates; but can you confirm the version of Python that is being used in that shell, and the version that pip is bound to?

It also appears that your in-IDE shell isn't running an activated virtual environment, which is another step that the tutorial mentions (again, in both the getting started guide, and in the tutorial itself). Can you confirm if you are using a virtual environment?

**Comment by Jvalal** [comment]
I don't think it's a virtual environment. I'm just using PyCharm and their UI is very misleading, to me.

When I go through project creation, it says, has "selected" python 3.7, however when I go and check version it's clearly not running that. So, I'm not sure why the UI is telling me it is.  It's confusing, not your issue, but annoying to me nonetheless. 

![pycharm](https://user-images.githubusercontent.com/3803053/44072245-775d12a2-9f42-11e8-8818-b2cac39cfef4.gif)

**Comment by Ocupe** [comment]
@Jvalal if you use the latest version of PyCharm the virtual environment, in the Terminal, is activated by default.
Maybe because you use the system installation of python it refuses to do activate (wild guess).

Try to create a new virtual environment for your project by following the docs: https://www.jetbrains.com/help/pycharm-edu/configuring-language-interpreter.html

For more PyCharm related problems we are sadly the wrong project to provide support.

**Comment by Jvalal** [comment]
@freakboy3742 ok, still getting an error here.
1. In python 3.7.0
2. In a virtual env

j
![screen shot 2018-08-14 at 5 10 39 pm](https://user-images.githubusercontent.com/3803053/44125007-068cb9b2-9fe5-11e8-8848-c45ebb7dfb54.png)
