### ISSUE TITLE
Documentation formatting error

### ISSUE THREAD

**Issue by jChapman** [pybee/briefcase#67]
![image](https://user-images.githubusercontent.com/1152464/29991776-156bd472-8f5b-11e7-87ff-3e09f91f3830.png)

Under Tutorial 1, Use the same code...
https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-1.html#use-the-same-code-but-for-the-web

Probably a missing/misplaced newline, RST is fun

**Comment by leec1979** [comment]
The URL this issue refers to has changed since the issue was created. It's now https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-1.html#use-the-same-code-but-for-the-web (The 's' has been dropped from tutorials).

This looks ok to me now and, looking through the history it looks like @freakboy3742 fixed it with commit b6e512304202b12ba73ebaa6d432921a1dfac30c (Sorry, I haven't figured out how to link to commits yet :( ).

**Comment by freakboy3742** [comment]
Thanks for looking into this @leec1979!
